// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SubfolderWatermarks
{
    internal sealed partial class Vsix
    {
        public const string Id = "SubfolderWatermarks.983b151f-4a54-43ba-9927-f9ec0f4f5cff";
        public const string ProductName = "SubfolderWatermarks";
        public const string OptionGroupHeader = "Watermarks";
        public const string OptionSectionWatermarkHeader = "Watermark";
        public const string OptionSectionTextHeader = "Text";
        public const string OptionSectionBackgroundHeader = "Background";
        public const string OptionSectionMiscHeader = "Misc.";
        public const string OptionPageName = "General";
        public const string ProfileObjectName = "General";
        public const string Description = @"Add a configurable watermark to the editor for files in specific project subfolders.";
        public const string Language = "en-US";
        public const string Version = "1.8.3";
        public const string Author = "Programount Inc.";
        public const string Tags = "";
    }
}
